require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ManualInstructionsController do

  # This should return the minimal set of attributes required to create a valid
  # ManualInstruction. As you add validations to ManualInstruction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ManualInstructionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all manual_instructions as @manual_instructions" do
      manual_instruction = ManualInstruction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:manual_instructions).should eq([manual_instruction])
    end
  end

  describe "GET show" do
    it "assigns the requested manual_instruction as @manual_instruction" do
      manual_instruction = ManualInstruction.create! valid_attributes
      get :show, {:id => manual_instruction.to_param}, valid_session
      assigns(:manual_instruction).should eq(manual_instruction)
    end
  end

  describe "GET new" do
    it "assigns a new manual_instruction as @manual_instruction" do
      get :new, {}, valid_session
      assigns(:manual_instruction).should be_a_new(ManualInstruction)
    end
  end

  describe "GET edit" do
    it "assigns the requested manual_instruction as @manual_instruction" do
      manual_instruction = ManualInstruction.create! valid_attributes
      get :edit, {:id => manual_instruction.to_param}, valid_session
      assigns(:manual_instruction).should eq(manual_instruction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ManualInstruction" do
        expect {
          post :create, {:manual_instruction => valid_attributes}, valid_session
        }.to change(ManualInstruction, :count).by(1)
      end

      it "assigns a newly created manual_instruction as @manual_instruction" do
        post :create, {:manual_instruction => valid_attributes}, valid_session
        assigns(:manual_instruction).should be_a(ManualInstruction)
        assigns(:manual_instruction).should be_persisted
      end

      it "redirects to the created manual_instruction" do
        post :create, {:manual_instruction => valid_attributes}, valid_session
        response.should redirect_to(ManualInstruction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved manual_instruction as @manual_instruction" do
        # Trigger the behavior that occurs when invalid params are submitted
        ManualInstruction.any_instance.stub(:save).and_return(false)
        post :create, {:manual_instruction => { "title" => "invalid value" }}, valid_session
        assigns(:manual_instruction).should be_a_new(ManualInstruction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ManualInstruction.any_instance.stub(:save).and_return(false)
        post :create, {:manual_instruction => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested manual_instruction" do
        manual_instruction = ManualInstruction.create! valid_attributes
        # Assuming there are no other manual_instructions in the database, this
        # specifies that the ManualInstruction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ManualInstruction.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => manual_instruction.to_param, :manual_instruction => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested manual_instruction as @manual_instruction" do
        manual_instruction = ManualInstruction.create! valid_attributes
        put :update, {:id => manual_instruction.to_param, :manual_instruction => valid_attributes}, valid_session
        assigns(:manual_instruction).should eq(manual_instruction)
      end

      it "redirects to the manual_instruction" do
        manual_instruction = ManualInstruction.create! valid_attributes
        put :update, {:id => manual_instruction.to_param, :manual_instruction => valid_attributes}, valid_session
        response.should redirect_to(manual_instruction)
      end
    end

    describe "with invalid params" do
      it "assigns the manual_instruction as @manual_instruction" do
        manual_instruction = ManualInstruction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ManualInstruction.any_instance.stub(:save).and_return(false)
        put :update, {:id => manual_instruction.to_param, :manual_instruction => { "title" => "invalid value" }}, valid_session
        assigns(:manual_instruction).should eq(manual_instruction)
      end

      it "re-renders the 'edit' template" do
        manual_instruction = ManualInstruction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ManualInstruction.any_instance.stub(:save).and_return(false)
        put :update, {:id => manual_instruction.to_param, :manual_instruction => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested manual_instruction" do
      manual_instruction = ManualInstruction.create! valid_attributes
      expect {
        delete :destroy, {:id => manual_instruction.to_param}, valid_session
      }.to change(ManualInstruction, :count).by(-1)
    end

    it "redirects to the manual_instructions list" do
      manual_instruction = ManualInstruction.create! valid_attributes
      delete :destroy, {:id => manual_instruction.to_param}, valid_session
      response.should redirect_to(manual_instructions_url)
    end
  end

end
